# Generated by Django 3.0.7 on 2020-07-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200707_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogentrypage',
            old_name='categories',
            new_name='category',
        ),
    ]
