# Generated by Django 3.0.7 on 2020-07-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_auto_20200708_2120"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogentrypage",
            name="CoverImageType",
            field=models.BooleanField(
                default=True, help_text="screen width cover image"
            ),
        ),
    ]
