# Generated by Django 3.0.7 on 2020-07-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_blogentrypage_coverimagetype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogentrypage",
            old_name="CoverImageType",
            new_name="ScreenWidthCoverImage",
        ),
    ]
