# Generated by Django 3.0.7 on 2020-07-09 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_auto_20200709_0953"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogentrypage",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="blog.BlogPageCategory",
            ),
        ),
    ]
