# Generated by Django 3.0.7 on 2020-12-18 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20201215_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogentrypage',
            name='ScreenWidthCoverImage',
        ),
    ]
